{
  "sources": [
    {
      "generator": {
        "name": "artman",
        "version": "2.0.0",
        "dockerImage": "googleapis/artman@sha256:b3b47805231a305d0f40c4bf069df20f6a2635574e6d4259fac651d3f9f6e098"
      }
    },
    {
      "git": {
        "name": ".",
        "remote": "https://github.com/googleapis/python-error-reporting.git",
        "sha": "ca2619a6357350ea77d16559f875b89016455b7d"
      }
    },
    {
      "git": {
        "name": "googleapis",
        "remote": "https://github.com/googleapis/googleapis.git",
        "sha": "3f5f8a2258c6a41f9fbf7b80acbca631dda0a952",
        "internalRef": "308922843"
      }
    },
    {
      "git": {
        "name": "synthtool",
        "remote": "https://github.com/googleapis/synthtool.git",
        "sha": "01b6f23d24b27878b48667ce597876d66b59780e"
      }
    }
  ],
  "destinations": [
    {
      "client": {
        "source": "googleapis",
        "apiName": "errorreporting",
        "apiVersion": "v1beta1",
        "language": "python",
        "generator": "gapic",
        "config": "google/devtools/clouderrorreporting/artman_errorreporting.yaml"
      }
    }
  ]
}